swagger: "2.0"
info:
  version: 1.0.0
  title: Desafio CVC
  license:
    name: OpenSource
host: TBD
basePath: /v1
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /hotels:
    get:
      summary: Return Hotels by CityCode, Checkin and Checkout Date. Calculate totalPrice based number of pax/children and days.
      operationId: getHotels
      parameters:  
        - in: query
          name: CityCode
          required: true
          type: integer
          description: Code of City (1032 -Porto Seguro, 7110 - Rio de Janeiro, 9626 - São Paulo)

        - in: query
          name: checkIn
          required: true          
          type: string
          description: Date of CheckIn(DD/MM/YYYY) uses percent-encoded. For example, / is encoded as %2F (or %2f).

        - in: query
          name: checkOut
          required: true          
          type: string
          description: Date of CheckOUT(DD/MM/YYYY) uses percent-encoded. For example, / is encoded as %2F (or %2f).

        - in: query
          name: qtdPax
          required: true          
          type: integer
          description:  Mumber of Pax on the trip

        - in: query
          name: qtdChd
          required: true          
          type: integer
          description: Mumber of Children on the trip
          
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/hotel'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/error'
definitions:
  hotel:
    type: "object"
    required:
      - id
      - cityName    
    properties:
      id:
        type: integer
        format: int64
      cityName:
        type: string
      rooms:
        type: array
        items:
          $ref: '#/definitions/rooms'
        
  rooms:
    type: "object"
    required:
      - roomID
      - categoryName
      - totalPrice
    properties:
      roomID:
        type: integer
        format: int64
      categoryName:
        type: string
      totalPrice:
        type: number
      priceDetail:
        $ref: '#/definitions/priceDetail'
        
  priceDetail:        
    type: "object"
    required:
      - pricePerDayAdult
      - pricePerDayChild
    properties:
      pricePerDayAdult:
        type: number
      pricePerDayChild:  
        type: number

  error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string